// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqVQnVfaKBOA6BXpTvrhfzwv9TC07WTCI',
    appId: '1:298500679782:web:905cd8d1c1c59f93a065a7',
    messagingSenderId: '298500679782',
    projectId: 'smart-home-automation-f1984',
    authDomain: 'smart-home-automation-f1984.firebaseapp.com',
    storageBucket: 'smart-home-automation-f1984.firebasestorage.app',
    measurementId: 'G-D42JD30MQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1V8gNxCf79DcCuDaaqFdt4X5ZI6kAON0',
    appId: '1:298500679782:android:4891e280d81caef8a065a7',
    messagingSenderId: '298500679782',
    projectId: 'smart-home-automation-f1984',
    storageBucket: 'smart-home-automation-f1984.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0-RI-nZ3KA4-2dnRJQEV_zxJlIYteJo4',
    appId: '1:298500679782:ios:05bb7100d0917ca9a065a7',
    messagingSenderId: '298500679782',
    projectId: 'smart-home-automation-f1984',
    storageBucket: 'smart-home-automation-f1984.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0-RI-nZ3KA4-2dnRJQEV_zxJlIYteJo4',
    appId: '1:298500679782:ios:05bb7100d0917ca9a065a7',
    messagingSenderId: '298500679782',
    projectId: 'smart-home-automation-f1984',
    storageBucket: 'smart-home-automation-f1984.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqVQnVfaKBOA6BXpTvrhfzwv9TC07WTCI',
    appId: '1:298500679782:web:9960a3cf2297ff96a065a7',
    messagingSenderId: '298500679782',
    projectId: 'smart-home-automation-f1984',
    authDomain: 'smart-home-automation-f1984.firebaseapp.com',
    storageBucket: 'smart-home-automation-f1984.firebasestorage.app',
    measurementId: 'G-CJJY7X3Y40',
  );
}
